apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: ready-if-services-ready
  name: ready-if-services-ready
spec:
  containers:
    - image: nginx:1.16.1-alpine
      name: ready-if-services-ready
      resources: {}
      livenessProbe:
        exec:
          command:
            - 'true'
      readinessProbe:
        exec:
          command:
            - sh
            - -c
            - 'wget -T2 -O- http://service-am-i-ready:80'
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}