apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: api-explorer-binding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
  - kind: ServiceAccount
    name: api-explorer
    namespace: default